[project]
name = "interview-practice"
version = "0.1.0"
description = "Practicing for coding interviews"
readme = "README.md"
requires-python = ">=3.10"

[tool.pyright]
typeCheckingMode = "strict"

[tool.ruff]
select = ["E", "F", "N", "I", "PL"]
